#


spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/idf?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8082

# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://hello:word@localhost:8761/eureka/
  # 使用ip进行注册
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:8081/users/current
#    client:
#      #client-id: zuul_2
#      #client-secret: 123456
#      access-token-uri: http://localhost:8081/oauth/token
#      grant-type: client_credentials,password
#      scope: select


security:
  oauth2:
    client:
      client-id: zuul_1
      client-secret: 123456
      access-token-uri: http://localhost:8081/oauth/token
      user-authorization-uri: http://localhost:8081/oauth/authorize
    resource:
      user-info-uri: http://localhost:8081/users/current


management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8668


logging:
  level:
    org:
      springframework: DEBUG