#



spring:
  devtools:
    restart:
      enabled=true:
  application:
    message: Hello Phil
    name: mng-web
  datasource:
    url: jdbc:mysql://localhost:3306/idf?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
  resources:
    cache:
      period: 0
  messages:
    basename: i18n/messages
    encoding: UTF-8
  http:
    encoding:
      force: true
  jackson:
    time-zone: Asia/Shanghai
server:
  servlet:
    context-path: /idf
  port: 80
  tomcat:
    uri-encoding: utf-8
  forward-headers-strategy: framework

# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://hello:word@localhost:8761/eureka/
# 使用ip进行注册
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8081/users/current
    client:
      access-token-uri: http://localhost:8081/oauth/token
      grant-type: client_credentials,password
      scope: select
#debug: true

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
logging:
  level:

    root: info
    org:
      springframework:
        security: debug
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
        engine:
          query:
            HQLQueryPlan: debug
          QueryParameters: debug
        SQL: debug
