name: hello
password: word

spring:
  application:
    name: eureka-server
  security:
    basic:
      enabled: true
    user:
      name: ${name}
      password: ${password}
  profiles:
    active: eureka-server-single

eureka:
  environment: Eigpay Dev
  datacenter: Eigpay Default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8666
---
spring:
  profiles: eureka-server-single
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server-single
    prefer-ip-address: true
  server:
    peer-eureka-status-refresh-time-interval-ms: 1000
  client:
    register-with-eureka: false
    # 指示此客户端是否应从eureka服务器获取eureka注册表信息。
    fetch-registry: false

---
spring:
  profiles: eureka-server-01
server:
  port: 7777
eureka:
  instance:
    hostname: eureka-server1
  server:
    peer-eureka-nodes-update-interval-ms: 10000 #默认是10分钟即600000，这里为了验证改为10秒
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${name}:${password}@eureka-server2:7778/eureka/,http://${name}:${password}@eureka-server3:7779/eureka/

---
spring:
  profiles: eureka-server-02
server:
  port: 7778
eureka:
  instance:
    hostname: eureka-server2
  server:
    peer-eureka-nodes-update-interval-ms: 10000 #
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${name}:${password}@eureka-server1:7777/eureka/,http://${name}:${password}@eureka-server3:7779/eureka/
---
spring:
  profiles: eureka-server-03
server:
  port: 7779
eureka:
  instance:
    hostname: eureka-server3
  server:
    peer-eureka-nodes-update-interval-ms: 10000 #
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${name}:${password}@eureka-server1:7777/eureka/,http://${name}:${password}@eureka-server2:7778/eureka/