#


spring:
  application:
    name: oauth-server
  datasource:
    url: jdbc:mysql://localhost:3306/idf?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  security:
    user:
      name: user
      password: helloword
server:
  port: 8081

# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://hello:word@localhost:8761/eureka/
# 使用ip进行注册
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}




management:
  endpoints:
    web:
      exposure:
       include: "*"
  server:
    port: 8667
logging:
  level:
    org:
      springframework:
        security: DEBUG